
package nossadistribuidora.view;

import Patterns.CadRespFormaPagamento.AbstractPagamentoHandler;
import Patterns.CadRespFormaPagamento.FormaDePagamento;
import Patterns.FabricaProdutoComboBox;
import Util.ConverteDatas;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import nossadistribuidora.controller.ClienteController;
import nossadistribuidora.controller.EnderecoController;
import nossadistribuidora.controller.ProdutoAguaController;
import nossadistribuidora.controller.ProdutoGasController;
import nossadistribuidora.controller.VendaController;
import nossadistribuidora.model.Cliente;
import nossadistribuidora.model.Produto;
import nossadistribuidora.model.ProdutoAgua;
import nossadistribuidora.model.ProdutoGas;
import nossadistribuidora.model.Venda;

/**
 *
 * @author Giseli
 */

/*Classe que exibe a tela para receber as informações relativas a venda como
*Cliente, Lista de produtos, valor e data.
*/
public class VendaView extends javax.swing.JFrame {

    private VendaController vendaController;
    private ClienteController clienteController;
    private EnderecoController enderecoController;
    private ProdutoAguaController aguaController;
    private ProdutoGasController gasController;
    
    private int cont = 0; //Contador que controla a inserção de itens na tabela de itens da venda.
    private float valorTotal = 0; //Variável que calcula o valor total da venda de acordo com os produtos inseridos
    private List<Produto> lstProdutos;
    private ArrayList<Integer> lstQuantidadeProduto;
    /*
    *Construtor que cria a instancia do controller necessário para as operações no banco e
    *criação do botao com os produtos cadastrados no banco de dados.
    */
    public VendaView() {
        vendaController = new VendaController();
        clienteController = new ClienteController();
        enderecoController = new EnderecoController();
        aguaController = new ProdutoAguaController();
        gasController = new ProdutoGasController();
        lstProdutos = new ArrayList<>();
        lstQuantidadeProduto = new ArrayList<Integer>();
        initComponents();
        jftDataVenda.setValue(Calendar.getInstance().getTime());//seta a data da venda com a data atual do sistema
    }
    
    /*
    *Get's dos controladores.
    */
    public VendaController getVendaController() {
        return vendaController;
    }
    
    public ClienteController getClienteController(){
        return clienteController;
    }

    public EnderecoController getEnderecoController(){
        return enderecoController;
    }
    
    public ProdutoAguaController getAguaController(){
        return aguaController;
    }
    
    public ProdutoGasController getGasController(){
        return gasController;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbSalvar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jbBuscarVenda = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtCodigoVenda = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jtValorTotal = new javax.swing.JTextField();
        jbBuscarCliente = new javax.swing.JButton();
        jftDataPagamento = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jtNomeCliente = new javax.swing.JTextField();
        jpEndereco = new javax.swing.JPanel();
        jtEnderecoCep = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtEnderecoRua = new javax.swing.JTextField();
        jtEnderecoNumero = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtEnderecoBairro = new javax.swing.JTextField();
        jtEnderecoCidade = new javax.swing.JTextField();
        jcEnderecoEstado = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jtAtivacao = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jtStatusPagamento = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jtTelefone = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jtCodigoCliente = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbListaProdutos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jcbProduto = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jcbMarca = new javax.swing.JComboBox<>();
        jbAdicionarProduto = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jftDataVenda = new javax.swing.JFormattedTextField();
        jcFormaDePagamento = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jtDesconto = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jcQuantidadeProduto = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Venda");
        setPreferredSize(new java.awt.Dimension(660, 700));
        setSize(new java.awt.Dimension(700, 0));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jbSalvar.setText("Salvar");
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jbExcluir.setText("Excluir");
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jbBuscarVenda.setText("Buscar");
        jbBuscarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarVendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbBuscarVenda)
                .addGap(18, 18, 18)
                .addComponent(jbSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbCancelar)
                .addGap(125, 125, 125))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSalvar)
                    .addComponent(jbCancelar)
                    .addComponent(jbExcluir)
                    .addComponent(jbBuscarVenda))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jLabel1.setText("Cliente:");

        jLabel3.setText("Código:");

        jLabel11.setText("Valor total:");

        jtValorTotal.setEditable(false);

        jbBuscarCliente.setText("Buscar");
        jbBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarClienteActionPerformed(evt);
            }
        });

        jftDataPagamento.setColumns(1);
        jftDataPagamento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        try{ 
            javax.swing.text.MaskFormatter data= new javax.swing.text.MaskFormatter("##/##/####");
            jftDataPagamento = new javax.swing.JFormattedTextField(data);
        }
        catch (Exception e){
        }

        jLabel5.setText("Data de pagamento:");

        jpEndereco.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Endereço", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));
        jpEndereco.setToolTipText("Informações");

        jtEnderecoCep.setEditable(false);

        jLabel4.setText("CEP:");

        jLabel6.setText("Rua:");

        jLabel7.setText("Numero:");

        jtEnderecoRua.setEditable(false);

        jtEnderecoNumero.setEditable(false);

        jLabel8.setText("Bairro:");

        jLabel9.setText("Cidade:");

        jLabel10.setText("Estado:");

        jtEnderecoBairro.setEditable(false);

        jtEnderecoCidade.setEditable(false);

        jcEnderecoEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        jcEnderecoEstado.setEnabled(false);

        jLabel12.setText("Ativação:");

        jtAtivacao.setEditable(false);

        jLabel13.setText("Pagamento:");

        jtStatusPagamento.setEditable(false);

        jLabel17.setText("Telefone:");

        jtTelefone.setEditable(false);

        jLabel19.setText("Codigo Cliente:");

        jtCodigoCliente.setEditable(false);

        javax.swing.GroupLayout jpEnderecoLayout = new javax.swing.GroupLayout(jpEndereco);
        jpEndereco.setLayout(jpEnderecoLayout);
        jpEnderecoLayout.setHorizontalGroup(
            jpEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEnderecoLayout.createSequentialGroup()
                .addGroup(jpEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpEnderecoLayout.createSequentialGroup()
                        .addGroup(jpEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addGroup(jpEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpEnderecoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcEnderecoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpEnderecoLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jtEnderecoCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jpEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13))
                                .addGroup(jpEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtTelefone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jpEnderecoLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jpEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jpEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jtAtivacao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jtEnderecoNumero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jtStatusPagamento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(jpEnderecoLayout.createSequentialGroup()
                        .addGroup(jpEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpEnderecoLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtEnderecoBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jpEnderecoLayout.createSequentialGroup()
                                    .addComponent(jLabel19)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jtCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jpEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jpEnderecoLayout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(jtEnderecoCep))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpEnderecoLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(jtEnderecoRua, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpEnderecoLayout.setVerticalGroup(
            jpEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEnderecoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpEnderecoLayout.createSequentialGroup()
                        .addGroup(jpEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpEnderecoLayout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(jLabel12)
                                .addGap(16, 16, 16)
                                .addComponent(jLabel13))
                            .addGroup(jpEnderecoLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jpEnderecoLayout.createSequentialGroup()
                        .addGroup(jpEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(jtCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpEnderecoLayout.createSequentialGroup()
                                .addGroup(jpEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jtEnderecoCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jpEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jtEnderecoRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jpEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtEnderecoBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jpEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jpEnderecoLayout.createSequentialGroup()
                                        .addGroup(jpEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel9)
                                            .addComponent(jtEnderecoCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(32, 32, 32))
                                    .addGroup(jpEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel10)
                                        .addComponent(jcEnderecoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jpEnderecoLayout.createSequentialGroup()
                                .addGroup(jpEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtEnderecoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jpEnderecoLayout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(jtAtivacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtStatusPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53))))))
        );

        jtbListaProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Marca", "capacidade/Peso", "Valor Un.", "Quantidade"
            }
        ));
        jScrollPane1.setViewportView(jtbListaProdutos);

        jLabel2.setText("Produto:");

        jcbProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Água", "Gás" }));
        jcbProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbProdutoActionPerformed(evt);
            }
        });

        jLabel14.setText("Marca:");

        jbAdicionarProduto.setText("Adicionar");
        jbAdicionarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAdicionarProdutoActionPerformed(evt);
            }
        });

        jLabel15.setText("Data da venda:");

        jftDataVenda.setEditable(false);
        jftDataVenda.setColumns(1);
        jftDataVenda.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        jcFormaDePagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Dinheiro", "Cartão" }));

        jLabel21.setText("Forma de pagamento:");

        jLabel16.setText("Desconto:");

        jcQuantidadeProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        jLabel18.setText("Quantidade:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addGap(18, 18, 18)
                                        .addComponent(jftDataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jtDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(219, 219, 219)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel21)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jcFormaDePagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel11))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jftDataPagamento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtValorTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jcbProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcbMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcQuantidadeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbAdicionarProduto)))
                        .addGap(47, 47, 47))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtCodigoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(jbBuscarCliente)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jpEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(37, 37, 37))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtCodigoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jbBuscarCliente)
                    .addComponent(jtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel14)
                    .addComponent(jcbMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbAdicionarProduto)
                    .addComponent(jcQuantidadeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jftDataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jftDataPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcFormaDePagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jpEndereco.getAccessibleContext().setAccessibleName("Informações");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 603, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
       
        /*
        *Adiciona uma venda a partir do valor "vazio" no campo 'código' da compra
        *caso nao haja valor: salva os dados da venda;
        *caso haja valor: informa que a venda nao pode ser registrada quando informado
        *o numero da venda(é gerado altomáticamente).
        */
        if(jtCodigoVenda.getText().equals("")){
            Venda venda = new Venda();
            
            //verifica se a data de pagamento é maior ou igual a data da compra
            ConverteDatas converterData = new ConverteDatas();
            try {
                Date dataVenda = converterData.converteData(jftDataVenda.getText());
                Date dataPagamento = converterData.converteData(jftDataPagamento.getText());
                //Se a data for maior ou igual a data da venda
                if((dataPagamento.after(dataVenda)) || (dataPagamento.equals(dataVenda))){
                    venda.setDataRecebimento(dataPagamento);
            
            
                    Cliente cliente = getClienteController().buscaClientePorId(Integer.parseInt(jtCodigoCliente.getText()));
                    venda.setCliente(cliente);
                    venda.setListaDeProdutos(lstProdutos);
                    venda.setData((Date)jftDataVenda.getValue());

                    //Verifica se há descondo definido para a venda
                    if(!(jtDesconto.getText().equals(""))){
                        venda.setDesconto(valorTotal);
                        valorTotal = valorTotal - Float.parseFloat(jtDesconto.getText());
                    }else{
                        venda.setDesconto(0);
                    }
                    venda.setValorTotal(valorTotal);
                    venda.setStatusEntrega("pendente");
                    venda.setStatusPagamento(false);
                    //Verifica a forma de pagamento
                    FormaDePagamento formaPagamento = new FormaDePagamento();
                    if(jcFormaDePagamento.getSelectedItem().equals("Dinheiro")){
                        formaPagamento.selecionaFormaDePagamento(AbstractPagamentoHandler.Pagamento.DINHEIRO,venda);
                    }else if(jcFormaDePagamento.getSelectedItem().equals("Cartão")){
                        formaPagamento.selecionaFormaDePagamento(AbstractPagamentoHandler.Pagamento.CARTAO, venda);
                    }
            
                    /*
                    *Envio das informações da venda para o respectivo controlador
                    *para que sejam realizadas as operações de inserção no banco de dados.
                    */
                    try {

                        getVendaController().inserir(venda);
                        cliente.setStatusPagamento(false);
                        getClienteController().alterar(cliente);
                        JOptionPane.showMessageDialog(this, "Venda inserida com sucesso!", 
                        "Inserir venda",JOptionPane.INFORMATION_MESSAGE);
                        dispose();
                    } catch (Exception ex) {
                        Logger.getLogger(VendaView.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }else{
                    JOptionPane.showMessageDialog(this, "Data de pagamento informada é inválida. Verifique essa informação e"
                            + "tente novamente!",
                            "Inserir venda",JOptionPane.INFORMATION_MESSAGE);
                } 
            } catch (ParseException ex) {
                Logger.getLogger(VendaView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            JOptionPane.showMessageDialog(this, "O campo 'Código' da venda deve estar vazio para inserção de nova venda. "
                    + "Verifique essa informação e tente novamente!", "Inserir venda",JOptionPane.INFORMATION_MESSAGE);
                dispose();
        }
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        
    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jbAdicionarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAdicionarProdutoActionPerformed

        
        /*
        *Recebe os valores selecionados para cada produto e adiciona os valores em cada linha da tabela de produtos
        */
        if(jcbProduto.getSelectedItem().equals("Gás")){
            ProdutoGas selecionado = (ProdutoGas)jcbMarca.getSelectedItem();
            //Verifica a disponibilidade de produto em estoque
            if(Integer.parseInt(jcQuantidadeProduto.getSelectedItem().toString())<= selecionado.getQuantidadeEstoque()){
                jtbListaProdutos.setValueAt(selecionado.getID(), cont, 0);
                jtbListaProdutos.setValueAt(selecionado.getNome(), cont, 1);
                jtbListaProdutos.setValueAt(selecionado.getMarca(), cont, 2);
                jtbListaProdutos.setValueAt(selecionado.getPeso(), cont, 3);
                jtbListaProdutos.setValueAt(selecionado.getValor(), cont, 4);
                jtbListaProdutos.setValueAt(jcQuantidadeProduto.getSelectedItem(), cont, 5);
                lstProdutos.add(selecionado); //Adiciona o produto selecionado à lista de produtos da venda
                //Adiciona a quantidade do produto selecionado em uma lista.
                lstQuantidadeProduto.add(Integer.parseInt(jcQuantidadeProduto.getSelectedItem().toString()));
                //Reduz a quantidade de produto selecionada da quantidade de produto em estoque
                selecionado.setQuantidadeEstoque(selecionado.getQuantidadeEstoque()-lstQuantidadeProduto.get(cont));
                try {
                    getGasController().alterar(selecionado);
                } catch (Exception ex) {
                    Logger.getLogger(VendaView.class.getName()).log(Level.SEVERE, null, ex);
                }
                valorTotal = valorTotal+(selecionado.getValor()*lstQuantidadeProduto.get(cont));
                jtValorTotal.setText(String.valueOf(valorTotal));
                cont++;
            } else{
                JOptionPane.showMessageDialog(this, "Quantidade do produto selecionado está indisponível. "
                        + "Selecione outro valor e tente novamente!", "Inserir venda",JOptionPane.INFORMATION_MESSAGE);
            }
            
        }else if(jcbProduto.getSelectedItem().equals("Água")){
            ProdutoAgua selecionado = (ProdutoAgua)jcbMarca.getSelectedItem();
            if(Integer.parseInt(jcQuantidadeProduto.getSelectedItem().toString())<= selecionado.getQuantidadeEstoque()){
                jtbListaProdutos.setValueAt(selecionado.getID(), cont, 0);
                jtbListaProdutos.setValueAt(selecionado.getNome(), cont, 1);
                jtbListaProdutos.setValueAt(selecionado.getMarca(), cont, 2);
                jtbListaProdutos.setValueAt(selecionado.getCapacidade(), cont, 3);
                jtbListaProdutos.setValueAt(selecionado.getValor(), cont, 4);
                jtbListaProdutos.setValueAt(jcQuantidadeProduto.getSelectedItem(), cont, 5);
                lstProdutos.add(selecionado);//Adiciona o produto selecionado à lista de produtos da venda
                //Adiciona a quantidade do produto selecionado em uma lista.
                lstQuantidadeProduto.add(Integer.parseInt(jcQuantidadeProduto.getSelectedItem().toString()));
                //Reduz a quantidade de produto selecionada da quantidade de produto em estoque
                selecionado.setQuantidadeEstoque(selecionado.getQuantidadeEstoque()-lstQuantidadeProduto.get(cont));
                try {
                    getAguaController().alterar(selecionado);
                } catch (Exception ex) {
                    Logger.getLogger(VendaView.class.getName()).log(Level.SEVERE, null, ex);
                }
                valorTotal = valorTotal+(selecionado.getValor()*lstQuantidadeProduto.get(cont));
                jtValorTotal.setText(String.valueOf(valorTotal));
                cont++;
            }else{
                JOptionPane.showMessageDialog(this, "Quantidade do produto selecionado está indisponível. "
                    + "Selecione outro valor e tente novamente!", "Inserir venda",JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_jbAdicionarProdutoActionPerformed

    private void jcbProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbProdutoActionPerformed
        //Fabrica que cria o comboBox de acordo com o tipo de produto selecionado.
        FabricaProdutoComboBox.criaJComboBoxProduto(jcbProduto.getSelectedItem().toString(), jcbMarca);
    }//GEN-LAST:event_jcbProdutoActionPerformed

    private void jbBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarClienteActionPerformed
        /*Codigo para buscar os dados no banco e mostrar no Frame
        *Busca o Cliente por nome
        */
        Cliente cliente = null;
        
        //Testa se o campo nome está vazio e busca no banco com operação específica
        if(!(jtNomeCliente.getText().equals(""))){
            cliente = getClienteController().buscaClientePorNome(jtNomeCliente.getText()); //recebe null caso o cliente não exista
        }
        
        /*
        *Exibe as informações do cliente nos jTextField da janela.
        */
        if(cliente != null){
            jtCodigoCliente.setText(Integer.toString(cliente.getCodigo()));
            jtNomeCliente.setText(cliente.getNome());
            jtTelefone.setText(cliente.getTelefone());
            jtEnderecoRua.setText(cliente.getEndereco().getRua());
            jtEnderecoNumero.setText(Integer.toString(cliente.getEndereco().getNumero()));
            jtEnderecoBairro.setText(cliente.getEndereco().getBairro());
            jtEnderecoCidade.setText(cliente.getEndereco().getCidade());
            jcEnderecoEstado.setSelectedItem(cliente.getEndereco().getEstado());
            jtEnderecoCep.setText(cliente.getEndereco().getCep());
            if(cliente.getStatusAtivacao() == true){
                jtAtivacao.setText("Ativo");
            }else{
                jtAtivacao.setText("Desativado");
                //Informa que o cliente está desativo e oferece opção de reativação
                if(JOptionPane.showConfirmDialog(this, "Cliente informado está desativo, deseja reativar?",
                    "Buscar cliente",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
                    ClienteView clienteView = new ClienteView();
                    clienteView.setVisible(true);
                }else {
                    dispose();
                }
            
            }
            if(cliente.getStatusPagamento() == true){
                jtStatusPagamento.setText("Ok");
            }else{
                jtStatusPagamento.setText("Pendente");
                //Caso o cliente tenha status de pagamento pendente informa que a venda nao pode ser realizada
                JOptionPane.showMessageDialog(this, "O cliente informado possui pendência de pagamento!"
                        + " Regularizar situação para concluir operação.", 
                    "Buscar cliente",JOptionPane.INFORMATION_MESSAGE);
                dispose();
            }
            
            
        }   /*
            *Caso o dado para busca(nome) não tenha sido informado
            */
            else if(jtNomeCliente.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Informar nome do cliente para busca!", 
                    "Buscar cliente",JOptionPane.INFORMATION_MESSAGE);
            }
                /*
                *Caso o cliente cujos dados informados não exista, solicita o cadastro
                */
                else if(JOptionPane.showConfirmDialog(this, "Cliente não cadastrado, deseja cadastrar?",
                    "realizar novo cadastro?",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
                    ClienteView clienteView = new ClienteView();
                    clienteView.setVisible(true);
                    dispose();
                }else {
                    dispose();
                }
    }//GEN-LAST:event_jbBuscarClienteActionPerformed

    private void jbBuscarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarVendaActionPerformed
        /*Codigo para buscar os dados no banco e mostrar no Frame
        *Busca a venda por código
        */
        Venda venda = null;
        //Verifica se o numero da venda que se deseja buscar foi informado
        if(!(jtCodigoVenda.getText().equals(""))){
            venda = getVendaController().buscaVendaPorCodigo(Integer.parseInt(jtCodigoVenda.getText()));
        }
        /*
        *Exibe as informações da compra nos jTextField da janela.
        */
        if(venda != null){
            jtCodigoVenda.setText(String.valueOf(venda.getCodigo()));
            
            //Informações de cliente
            jtNomeCliente.setText(venda.getCliente().getNome());
            jtCodigoCliente.setText(String.valueOf(venda.getCliente().getCodigo()));
            jtEnderecoCep.setText(venda.getCliente().getEndereco().getCep());
            jtEnderecoRua.setText(venda.getCliente().getEndereco().getRua());
            jtEnderecoBairro.setText(venda.getCliente().getEndereco().getBairro());
            jtEnderecoCidade.setText(venda.getCliente().getEndereco().getCidade());
            jcEnderecoEstado.setSelectedItem(venda.getCliente().getEndereco().getEstado());
            jtbListaProdutos.setValueAt(5,0, 0);
            //Preenche a lista de produtos da compra e a quantidade respectiva de cada um
            //for(int indice = 0; indice < venda.getListaDeProdutos().size(); indice++){
            int indice = 0;
            for(Produto produto : venda.getListaDeProdutos()){ 
                int linha = venda.getListaDeProdutos().indexOf(produto);
                jtbListaProdutos.setValueAt(linha, linha, linha);
                if(venda.getListaDeProdutos().get(indice).getClass().equals(ProdutoAgua.class)){
                    System.out.println(venda.getListaDeProdutos().get(indice));
                    ProdutoAgua agua = (ProdutoAgua) venda.getListaDeProdutos().get(indice);
                    jtbListaProdutos.setValueAt(agua.getID(), indice, 0);
                    jtbListaProdutos.setValueAt(agua.getNome(), indice, 1);
                    jtbListaProdutos.setValueAt(agua.getMarca(), indice, 2);
                    jtbListaProdutos.setValueAt(agua.getCapacidade(), indice, 3);
                    jtbListaProdutos.setValueAt(agua.getValor(), indice, 4);
                    jtbListaProdutos.setValueAt(lstQuantidadeProduto.get(indice), indice, 5);
                }else if(venda.getListaDeProdutos().get(indice).getClass().equals(ProdutoGas.class)){
                    System.out.println(venda.getListaDeProdutos().get(indice));
                    ProdutoGas gas = (ProdutoGas) venda.getListaDeProdutos().get(indice);
                    jtbListaProdutos.setValueAt(gas.getID(), indice, 0);
                    jtbListaProdutos.setValueAt(gas.getNome(), indice, 1);
                    jtbListaProdutos.setValueAt(gas.getMarca(), indice, 2);
                    jtbListaProdutos.setValueAt(gas.getPeso(), indice, 3);
                    jtbListaProdutos.setValueAt(gas.getValor(), indice, 4);
                    jtbListaProdutos.setValueAt(lstQuantidadeProduto.get(indice), indice, 5);
                }
                indice++;
            }
            jftDataVenda.setValue(venda.getData());
            jftDataPagamento.setValue(venda.getDataRecebimento());
            jtDesconto.setText(String.valueOf(venda.getDesconto()));
            jtValorTotal.setText(String.valueOf(venda.getValorTotal()));
            jcFormaDePagamento.setSelectedItem(venda.getFormaDePagamento());
       }    /*
            *Caso o dado para busca(codigo da venda) não tenha sido informado
            */
            else if(jtCodigoVenda.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Informar o código da venda para busca", 
                    "Buscar venda",JOptionPane.INFORMATION_MESSAGE);
            }
                /*
                *Caso a venda cujos dados informados não exista
                */
            else{ JOptionPane.showMessageDialog(this, "A venda informada não existe! Verifique o código e tente novamente.", 
                    "Buscar venda",JOptionPane.INFORMATION_MESSAGE);
                    dispose();
                }
    }//GEN-LAST:event_jbBuscarVendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VendaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VendaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VendaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VendaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VendaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAdicionarProduto;
    private javax.swing.JButton jbBuscarCliente;
    private javax.swing.JButton jbBuscarVenda;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JComboBox<String> jcEnderecoEstado;
    private javax.swing.JComboBox<String> jcFormaDePagamento;
    private javax.swing.JComboBox<String> jcQuantidadeProduto;
    private javax.swing.JComboBox<String> jcbMarca;
    private javax.swing.JComboBox<String> jcbProduto;
    private javax.swing.JFormattedTextField jftDataPagamento;
    private javax.swing.JFormattedTextField jftDataVenda;
    private javax.swing.JPanel jpEndereco;
    private javax.swing.JTextField jtAtivacao;
    private javax.swing.JTextField jtCodigoCliente;
    private javax.swing.JTextField jtCodigoVenda;
    private javax.swing.JTextField jtDesconto;
    private javax.swing.JTextField jtEnderecoBairro;
    private javax.swing.JTextField jtEnderecoCep;
    private javax.swing.JTextField jtEnderecoCidade;
    private javax.swing.JTextField jtEnderecoNumero;
    private javax.swing.JTextField jtEnderecoRua;
    private javax.swing.JTextField jtNomeCliente;
    private javax.swing.JTextField jtStatusPagamento;
    private javax.swing.JTextField jtTelefone;
    private javax.swing.JTextField jtValorTotal;
    private javax.swing.JTable jtbListaProdutos;
    // End of variables declaration//GEN-END:variables
}
